import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import {
  Search,
  Wrench,
  Calendar,
  CheckCircle,
  XCircle,
  Clock,
  MapPin,
} from 'lucide-react';
import {
  API_BASE_URL,
  Machinery,
  MachineryType,
  listMachineryTypes,
  listMachineryByType,
  getMachineryHistory,
  type MachineryHistoryEntry,
  type MachineryImportPreviewRow,
  previewMachineryImport,
  commitMachineryImport,
  createMachinery,
  createMachineryType,
  updateMachineryType,
  updateMachinery,
  startMaintenance,
  endMaintenance,
} from '@/lib/api';
import { useAuth } from '@/contexts/AuthContext';
import { cn } from '@/lib/utils';

const MachineryPage = () => {
  const { accessToken, hasPrivilege } = useAuth();
  const [types, setTypes] = useState<MachineryType[]>([]);
  const [machines, setMachines] = useState<Machinery[]>([]);
  const [history, setHistory] = useState<MachineryHistoryEntry[]>([]);

  const [selectedType, setSelectedType] = useState<string>('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<'all' | 'OPERATIONAL' | 'MAINTENANCE' | 'OUT_OF_SERVICE'>('all');
  const [locationFilter, setLocationFilter] = useState('');
  const [selectedMachine, setSelectedMachine] = useState<Machinery | null>(null);
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [newAssetTag, setNewAssetTag] = useState('');
  const [newMachineName, setNewMachineName] = useState('');
  const [newTypeId, setNewTypeId] = useState<string>('');
  const [newLocation, setNewLocation] = useState('');
  const [newStatus, setNewStatus] = useState<'OPERATIONAL' | 'MAINTENANCE' | 'OUT_OF_SERVICE'>('OPERATIONAL');
  const [suggestedAssetTag, setSuggestedAssetTag] = useState<string | null>(null);
  const [isAssetTagAutoGenerated, setIsAssetTagAutoGenerated] = useState(false);
  const [validationErrors, setValidationErrors] = useState<{assetTag?: string; machineName?: string}>({});
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [isCreateTypeOpen, setIsCreateTypeOpen] = useState(false);
  const [editingTypeId, setEditingTypeId] = useState<number | null>(null);
  const [newTypeName, setNewTypeName] = useState('');
  const [newTypeDescription, setNewTypeDescription] = useState('');
  const [savingType, setSavingType] = useState(false);
  const [saveTypeError, setSaveTypeError] = useState<string | null>(null);
  const [isImportOpen, setIsImportOpen] = useState(false);
  const [importFile, setImportFile] = useState<File | null>(null);
  const [previewRows, setPreviewRows] = useState<MachineryImportPreviewRow[]>([]);
  const [importLoading, setImportLoading] = useState(false);
  const [importError, setImportError] = useState<string | null>(null);

  const [isEditOpen, setIsEditOpen] = useState(false);
  const [editAssetTag, setEditAssetTag] = useState('');
  const [editMachineName, setEditMachineName] = useState('');
  const [editTypeId, setEditTypeId] = useState<string>('');
  const [editLocation, setEditLocation] = useState('');
  const [editStatus, setEditStatus] =
    useState<'OPERATIONAL' | 'MAINTENANCE' | 'OUT_OF_SERVICE'>('OPERATIONAL');
  const [editSaving, setEditSaving] = useState(false);
  const [editError, setEditError] = useState<string | null>(null);
  const [editValidationErrors, setEditValidationErrors] = useState<{ assetTag?: string; machineName?: string }>({});
  
  const [maintenanceConfirmOpen, setMaintenanceConfirmOpen] = useState(false);
  const [maintenanceAction, setMaintenanceAction] = useState<'start' | 'end' | null>(null);
  const [maintenanceLoading, setMaintenanceLoading] = useState(false);

  const canManageMachinery = hasPrivilege('can_manage_machinery');

  // Normalization functions (same as bulk import)
  const normalizeDisplayName = (value: string): string => {
    const collapsed = value.trim().replace(/\s+/g, ' ');
    if (!collapsed) return '';
    return collapsed
      .split(' ')
      .map((word) =>
        word.length === 0 ? '' : word[0].toUpperCase() + word.slice(1).toLowerCase(),
      )
      .join(' ');
  };

  // Generate asset tag suggestion from machinery type
  const generateAssetTagSuggestion = (typeId: string): string | null => {
    if (!typeId) return null;
    const type = types.find((t) => String(t.MachineryTypeID) === typeId);
    if (!type) return null;
    
    // Derive code from type name (same logic as backend)
    const cleaned = type.TypeName.trim().toUpperCase();
    if (!cleaned) return 'MCH-001';
    const firstWord = cleaned.split(' ')[0];
    const letters = firstWord.replace(/[^A-Z0-9]/g, '');
    const base = letters.endsWith('S') && letters.length > 1 ? letters.slice(0, -1) : letters;
    const code = base || 'MCH';
    
    // Find next available number (check existing machines)
    let counter = 1;
    while (counter < 1000) {
      const candidate = `${code}-${counter.toString().padStart(3, '0')}`;
      const exists = machines.some((m) => m.code.toLowerCase() === candidate.toLowerCase());
      if (!exists) return candidate;
      counter++;
    }
    return `${code}-001`; // Fallback
  };

  // Update asset tag suggestion when type changes
  useEffect(() => {
    if (isCreateOpen && newTypeId && !newAssetTag) {
      const suggestion = generateAssetTagSuggestion(newTypeId);
      setSuggestedAssetTag(suggestion);
      setIsAssetTagAutoGenerated(true);
    } else if (newAssetTag) {
      setSuggestedAssetTag(null);
      setIsAssetTagAutoGenerated(false);
    }
  }, [newTypeId, newAssetTag, isCreateOpen, types, machines]);

  // Load machinery types on mount
  useEffect(() => {
    let cancelled = false;
    const loadTypes = async () => {
      try {
        const data = await listMachineryTypes({}, accessToken);
        if (!cancelled) {
          setTypes(data);
        }
      } catch {
        if (!cancelled) setTypes([]);
      }
    };
    void loadTypes();
    return () => {
      cancelled = true;
    };
  }, [accessToken]);

  // Helper to load machinery for current selection
  const loadMachinesForSelection = async (typeValue: string, token: string | null) => {
    if (!token || types.length === 0) {
      setMachines([]);
      setSelectedMachine(null);
      return;
    }

    if (typeValue === 'all') {
      // Load machinery for all types and combine
      const all: Machinery[] = [];
      for (const t of types) {
        try {
          const data = await listMachineryByType(t.MachineryTypeID, {}, token);
          all.push(...data);
        } catch {
          // ignore failures per type for now
        }
      }
      setMachines(all);
      setSelectedMachine(all[0] ?? null);
      return;
    }

    // Load machinery for a specific type
    try {
      const typeId = Number(typeValue);
      const data = await listMachineryByType(typeId, {}, token);
      setMachines(data);
      setSelectedMachine(data[0] ?? null);
    } catch {
      setMachines([]);
      setSelectedMachine(null);
    }
  };

  // Load machinery when selection or types change
  useEffect(() => {
    void loadMachinesForSelection(selectedType, accessToken);
  }, [selectedType, types, accessToken]);

  // Load history when selected machine changes
  useEffect(() => {
    if (!selectedMachine) {
      setHistory([]);
      return;
    }
    void (async () => {
      const data = await getMachineryHistory(selectedMachine.id, accessToken);
      setHistory(data);
    })();
  }, [selectedMachine, accessToken]);

  const filteredMachinery = useMemo(
    () =>
      machines.filter((machine) => {
        const typeName = types.find((t) => t.MachineryTypeID === machine.type_id)?.TypeName ?? '';
        const matchesSearch =
          !searchQuery.trim() ||
          machine.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
          machine.code.toLowerCase().includes(searchQuery.toLowerCase()) ||
          typeName.toLowerCase().includes(searchQuery.toLowerCase());

        const matchesType =
          selectedType === 'all' || String(machine.type_id) === selectedType;

        const matchesStatus =
          statusFilter === 'all' ||
          machine.status.toUpperCase() === statusFilter;

        const matchesLocation =
          !locationFilter.trim() ||
          (machine.location ?? '')
            .toLowerCase()
            .includes(locationFilter.toLowerCase());

        return matchesSearch && matchesType && matchesStatus && matchesLocation;
      }),
    [machines, types, searchQuery, selectedType, statusFilter, locationFilter],
  );

  const getStatusIcon = (status: Machinery['status']) => {
    const normalized = status.toUpperCase();
    switch (normalized) {
      case 'OPERATIONAL':
        return <CheckCircle className="h-4 w-4 text-success" />;
      case 'MAINTENANCE':
        return <Wrench className="h-4 w-4 text-warning" />;
      case 'OUT_OF_SERVICE':
        return <XCircle className="h-4 w-4 text-destructive" />;
    }
  };

  const formatDate = (dateString?: string) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
  };

  const formatDateTime = (dateString: string) => {
    return new Date(dateString).toLocaleString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Machinery</h1>
          <p className="mt-1 text-muted-foreground">
            Track and manage all machinery and equipment
          </p>
        </div>
        {canManageMachinery && (
          <div className="flex flex-col gap-2 sm:flex-row">
            <Button asChild className="w-full sm:w-auto">
              <Link to="/machinery/import">Bulk import</Link>
            </Button>
            <Button
              variant="outline"
              onClick={() => setIsCreateTypeOpen(true)}
              className="w-full sm:w-auto"
            >
              <Wrench className="mr-2 h-4 w-4" />
              New type
            </Button>
            <Button onClick={() => setIsCreateOpen(true)} className="w-full sm:w-auto">
              <Wrench className="mr-2 h-4 w-4" />
              New machinery
            </Button>
          </div>
        )}
      </div>

      {/* Bulk Import Dialog (deprecated in favor of /machinery/import page) */}
      {false && canManageMachinery && (
        <Dialog
          open={isImportOpen}
          onOpenChange={(open) => {
            setIsImportOpen(open);
            if (!open) {
              setImportFile(null);
              setPreviewRows([]);
              setImportError(null);
            }
          }}
        >
          <DialogContent className="max-w-3xl">
            <DialogHeader>
              <DialogTitle>Bulk import machinery</DialogTitle>
              <DialogDescription>
                Upload a CSV file to validate and import multiple machines at once.
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-4 py-2">
              <div className="space-y-2">
                <Label>Template</Label>
                <p className="text-xs text-muted-foreground">
                  Download the template, fill it in, then upload the completed file.
                </p>
                <a
                  href={`${API_BASE_URL}/api/v1/machinery/import/template`}
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex text-xs text-primary underline"
                >
                  Download CSV template
                </a>
              </div>
              <div className="space-y-2">
                <Label htmlFor="import_file">CSV file</Label>
                <Input
                  id="import_file"
                  type="file"
                  accept=".csv,text/csv"
                  onChange={(e) => {
                    const file = e.target.files?.[0] ?? null;
                    setImportFile(file);
                    setPreviewRows([]);
                    setImportError(null);
                  }}
                />
              </div>
              <div className="flex items-center justify-between">
                {importError && (
                  <p className="text-sm text-destructive">{importError}</p>
                )}
                <Button
                  variant="outline"
                  size="sm"
                  onClick={async () => {
                    if (!importFile) {
                      setImportError('Please select a CSV file first.');
                      return;
                    }
                    setImportLoading(true);
                    setImportError(null);
                    try {
                      const result = await previewMachineryImport(
                        importFile,
                        accessToken,
                      );
                      setPreviewRows(result.rows);
                    } catch (err) {
                      setImportError(
                        err instanceof Error
                          ? err.message
                          : 'Failed to preview import.',
                      );
                    } finally {
                      setImportLoading(false);
                    }
                  }}
                  disabled={importLoading || !importFile}
                >
                  {importLoading ? 'Validating…' : 'Validate file'}
                </Button>
              </div>

              {previewRows.length > 0 && (
                <div className="space-y-2">
                  <p className="text-xs text-muted-foreground">
                    Review detected rows. Rows with errors must be fixed before import.
                    Warnings indicate types that will be created automatically.
                  </p>
                  <div className="max-h-80 overflow-auto rounded-md border border-border">
                    <table className="w-full text-xs">
                      <thead className="bg-muted/60">
                        <tr>
                          <th className="px-2 py-1 text-left">Row</th>
                          <th className="px-2 py-1 text-left">Asset tag</th>
                          <th className="px-2 py-1 text-left">Name</th>
                          <th className="px-2 py-1 text-left">Type</th>
                          <th className="px-2 py-1 text-left">Location</th>
                          <th className="px-2 py-1 text-left">Status</th>
                          <th className="px-2 py-1 text-left">Issues</th>
                        </tr>
                      </thead>
                      <tbody>
                        {previewRows.map((row) => (
                          <tr
                            key={row.row_index}
                            className={
                              row.status === 'ERROR'
                                ? 'bg-destructive/5'
                                : row.status === 'WARN'
                                ? 'bg-warning/5'
                                : ''
                            }
                          >
                            <td className="px-2 py-1 align-top font-mono">
                              {row.row_index}
                            </td>
                            <td className="px-2 py-1 align-top">
                              {row.raw.asset_tag}
                            </td>
                            <td className="px-2 py-1 align-top">
                              {row.raw.machine_name}
                            </td>
                            <td className="px-2 py-1 align-top">
                              {row.raw.machinery_type}
                            </td>
                            <td className="px-2 py-1 align-top">
                              {row.raw.location}
                            </td>
                            <td className="px-2 py-1 align-top">
                              {row.raw.status}
                            </td>
                            <td className="px-2 py-1 align-top">
                              {row.issues.length === 0 ? (
                                <span className="text-xs text-muted-foreground">
                                  None
                                </span>
                              ) : (
                                <ul className="space-y-0.5 text-[11px] text-muted-foreground">
                                  {row.issues.map((issue, idx) => (
                                    <li key={idx}>• {issue}</li>
                                  ))}
                                </ul>
                              )}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}
            </div>
            <DialogFooter>
              <Button
                variant="outline"
                onClick={() => setIsImportOpen(false)}
                disabled={importLoading}
              >
                Cancel
              </Button>
              <Button
                onClick={async () => {
                  if (previewRows.length === 0) {
                    setImportError('Please validate a file before importing.');
                    return;
                  }
                  const hasErrors = previewRows.some(
                    (row) => row.status === 'ERROR',
                  );
                  if (hasErrors) {
                    setImportError(
                      'Cannot import while there are rows with errors. Fix the file and revalidate.',
                    );
                    return;
                  }
                  setImportLoading(true);
                  setImportError(null);
                  try {
                    const result = await commitMachineryImport(
                      previewRows,
                      accessToken,
                    );
                    if (result.failed_rows && result.failed_rows.length > 0) {
                      setImportError(
                        `Imported with some failures: ${result.failed_rows.length} rows.`,
                      );
                    } else {
                      // refresh current type's machinery
                      if (selectedType !== 'all') {
                        const typeId = Number(selectedType);
                        const data = await listMachineryByType(
                          typeId,
                          {},
                          accessToken,
                        );
                        setMachines(data);
                        setSelectedMachine(data[0] ?? null);
                      } else if (types[0]) {
                        const data = await listMachineryByType(
                          types[0].MachineryTypeID,
                          {},
                          accessToken,
                        );
                        setMachines(data);
                        setSelectedMachine(data[0] ?? null);
                      }
                      setIsImportOpen(false);
                    }
                  } catch (err) {
                    setImportError(
                      err instanceof Error
                        ? err.message
                        : 'Failed to import machinery.',
                    );
                  } finally {
                    setImportLoading(false);
                  }
                }}
                disabled={importLoading || previewRows.length === 0}
              >
                {importLoading ? 'Importing…' : 'Import'}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}

      {/* Global Filters */}
      <Card variant="glass">
        <CardContent className="space-y-3 p-4">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              placeholder="Search machinery name or type..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-9"
            />
          </div>
          <div className="grid grid-cols-1 gap-2 md:grid-cols-3">
            <div className="flex gap-2">
              <div className="flex-1">
              <Select value={selectedType} onValueChange={setSelectedType}>
                <SelectTrigger>
                  <SelectValue placeholder="Filter by type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Types</SelectItem>
                  {types.map((type) => (
                    <SelectItem
                      key={type.MachineryTypeID}
                      value={String(type.MachineryTypeID)}
                    >
                      {type.TypeName}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {canManageMachinery && selectedType !== 'all' && (
                <Button
                  variant="outline"
                  size="icon"
                  onClick={() => {
                    const typeId = Number(selectedType);
                    const type = types.find((t) => t.MachineryTypeID === typeId);
                    if (type) {
                      setEditingTypeId(typeId);
                      setNewTypeName(type.TypeName);
                      setNewTypeDescription(type.Description || '');
                      setIsCreateTypeOpen(true);
                    }
                  }}
                  title="Edit machinery type"
                >
                  <Wrench className="h-4 w-4" />
                </Button>
              )}
            </div>
            <Select
              value={statusFilter}
              onValueChange={(val) =>
                setStatusFilter(val as typeof statusFilter)
              }
            >
              <SelectTrigger>
                <SelectValue placeholder="Status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Statuses</SelectItem>
                <SelectItem value="OPERATIONAL">Operational</SelectItem>
                <SelectItem value="MAINTENANCE">Maintenance</SelectItem>
                <SelectItem value="OUT_OF_SERVICE">Out of Service</SelectItem>
              </SelectContent>
            </Select>
            <Input
              placeholder="Filter by location"
              value={locationFilter}
              onChange={(e) => setLocationFilter(e.target.value)}
            />
          </div>
        </CardContent>
      </Card>

      {/* Two-Panel Layout */}
      <div className="grid gap-6 lg:grid-cols-3">
        {/* Left Panel - List */}
        <div className="space-y-4 lg:col-span-1">
          <Card>
            <CardContent className="p-0">
              <ScrollArea className="h-[calc(100vh-300px)]">
                <div className="space-y-1 p-2">
                  {filteredMachinery.map((machine) => (
                    <button
                      key={machine.id}
                      onClick={() => setSelectedMachine(machine)}
                      className={cn(
                        'w-full rounded-lg p-3 text-left transition-all',
                        selectedMachine?.id === machine.id
                          ? 'bg-primary/10 border border-primary/30'
                          : 'hover:bg-muted/50 border border-transparent'
                      )}
                    >
                      <div className="flex items-start gap-3">
                        {getStatusIcon(machine.status)}
                        <div className="flex-1 space-y-1">
                          <p className="font-medium text-foreground">{machine.name}</p>
                          <p className="text-xs text-muted-foreground">{machine.code}</p>
                        <div className="flex items-center gap-2">
                          <Badge
                            // Map backend status into one of our badge variants where possible
                            variant={
                              machine.status.toUpperCase() === 'OPERATIONAL'
                                ? 'operational'
                                : machine.status.toUpperCase() === 'MAINTENANCE'
                                ? 'maintenance'
                                : machine.status.toUpperCase() === 'OUT_OF_SERVICE'
                                ? 'out_of_service'
                                : 'secondary'
                            }
                            className="text-xs"
                          >
                            {machine.status.replace(/_/g, ' ')}
                          </Badge>
                        </div>
                        </div>
                      </div>
                    </button>
                  ))}
                  {filteredMachinery.length === 0 && (
                    <div className="flex flex-col items-center gap-2 py-8 text-muted-foreground">
                      <Wrench className="h-8 w-8" />
                      <p>No machinery found</p>
                    </div>
                  )}
                </div>
              </ScrollArea>
            </CardContent>
          </Card>
        </div>

        {/* Right Panel - Details */}
        <div className="space-y-4 lg:col-span-2">
          {selectedMachine ? (
            <>
              {/* Machine Details */}
              <Card>
                <CardHeader className="flex flex-row items-start justify-between">
                  <div className="space-y-1">
                    <CardTitle className="flex items-center gap-2">
                      {selectedMachine.name}
                      <Badge
                        variant={
                          selectedMachine.status.toUpperCase() === 'OPERATIONAL'
                            ? 'operational'
                            : selectedMachine.status.toUpperCase() === 'MAINTENANCE'
                            ? 'maintenance'
                            : selectedMachine.status.toUpperCase() === 'OUT_OF_SERVICE'
                            ? 'out_of_service'
                            : 'secondary'
                        }
                      >
                        {selectedMachine.status.replace(/_/g, ' ')}
                      </Badge>
                    </CardTitle>
                    <CardDescription>
                      {selectedMachine.code} •{' '}
                      {types.find((t) => t.MachineryTypeID === selectedMachine.type_id)
                        ?.TypeName ?? 'Unknown type'}
                    </CardDescription>
                  </div>
                  <div className="flex gap-2">
                    {selectedMachine.status.toUpperCase() === 'MAINTENANCE' ? (
                      <Button
                        variant="default"
                        disabled={!canManageMachinery}
                        onClick={() => {
                          setMaintenanceAction('end');
                          setMaintenanceConfirmOpen(true);
                        }}
                      >
                        <CheckCircle className="mr-2 h-4 w-4" />
                        Move to Operational
                      </Button>
                    ) : (
                      <Button
                        variant="outline"
                        disabled={!canManageMachinery || selectedMachine.status.toUpperCase() === 'OUT_OF_SERVICE'}
                        onClick={() => {
                          setMaintenanceAction('start');
                          setMaintenanceConfirmOpen(true);
                        }}
                      >
                        <Wrench className="mr-2 h-4 w-4" />
                        Move to Maintenance
                      </Button>
                    )}
                    <Button
                      variant="outline"
                      disabled={!canManageMachinery}
                      onClick={() => {
                        if (!selectedMachine) return;
                        setEditAssetTag(selectedMachine.code);
                        setEditMachineName(selectedMachine.name);
                        setEditTypeId(String(selectedMachine.type_id));
                        setEditLocation(selectedMachine.location ?? '');
                        setEditStatus(
                          (selectedMachine.status.toUpperCase() as
                            | 'OPERATIONAL'
                            | 'MAINTENANCE'
                            | 'OUT_OF_SERVICE') ?? 'OPERATIONAL',
                        );
                        setEditValidationErrors({});
                        setEditError(null);
                        setIsEditOpen(true);
                      }}
                    >
                      <Wrench className="mr-2 h-4 w-4" />
                      Edit machinery
                    </Button>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                    <div className="space-y-1 rounded-lg bg-muted/30 p-3">
                      <div className="flex items-center gap-2 text-muted-foreground">
                        <MapPin className="h-4 w-4" />
                        <span className="text-xs">Location</span>
                      </div>
                      <p className="font-medium">{selectedMachine.location ?? 'N/A'}</p>
                    </div>
                    <div className="space-y-1 rounded-lg bg-muted/30 p-3">
                      <div className="flex items-center gap-2 text-muted-foreground">
                        <Calendar className="h-4 w-4" />
                        <span className="text-xs">Status</span>
                      </div>
                      <p className="font-medium">
                        {selectedMachine.status.replace(/_/g, ' ')}
                      </p>
                    </div>
                    <div className="space-y-1 rounded-lg bg-muted/30 p-3">
                      <div className="flex items-center gap-2 text-muted-foreground">
                        <Wrench className="h-4 w-4" />
                        <span className="text-xs">Type</span>
                      </div>
                      <p className="font-medium">
                        {types.find((t) => t.MachineryTypeID === selectedMachine.type_id)
                          ?.TypeName ?? 'Unknown'}
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Maintenance History */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg">Maintenance History</CardTitle>
                  <CardDescription>Recent maintenance activities and records</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="relative space-y-0">
                    {/* Timeline Line */}
                    <div className="absolute left-[17px] top-2 h-[calc(100%-16px)] w-0.5 bg-border" />

                    {history.map((entry) => (
                      <div key={entry.id} className="relative flex gap-4 pb-6 last:pb-0">
                        {/* Timeline Dot */}
                        <div className="relative z-10 flex h-9 w-9 flex-shrink-0 items-center justify-center rounded-full bg-card border-2 border-border">
                          <Wrench className="h-4 w-4 text-muted-foreground" />
                        </div>
                        
                        {/* Content */}
                        <div className="flex-1 space-y-1 pt-1">
                          <div className="flex items-center justify-between">
                            <p className="font-medium text-foreground">
                              {entry.event_type.replace(/_/g, ' ')}
                            </p>
                            <p className="text-xs text-muted-foreground">
                              {formatDateTime(entry.created_at)}
                            </p>
                          </div>
                          <p className="text-sm text-muted-foreground">
                            {entry.description || entry.notes}
                          </p>
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </>
          ) : (
            <Card className="flex h-96 items-center justify-center">
              <div className="text-center text-muted-foreground">
                <Wrench className="mx-auto h-12 w-12 mb-4" />
                <p>Select a machine to view details</p>
              </div>
            </Card>
          )}
        </div>
      </div>

      {/* Create/Edit Machinery Type Dialog */}
      {canManageMachinery && (
        <Dialog
          open={isCreateTypeOpen}
          onOpenChange={(open) => {
            setIsCreateTypeOpen(open);
            if (!open) {
              setNewTypeName('');
              setNewTypeDescription('');
              setEditingTypeId(null);
              setSaveTypeError(null);
            }
          }}
        >
          <DialogContent>
            <DialogHeader>
              <DialogTitle>
                {editingTypeId ? 'Edit machinery type' : 'New machinery type'}
              </DialogTitle>
              <DialogDescription>
                {editingTypeId
                  ? 'Update the machinery type details.'
                  : 'Define a new machinery category (e.g., Pumps, Conveyors, Motors).'}
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-4 py-2">
              <div className="space-y-2">
                <Label htmlFor="type_name">Type name</Label>
                <Input
                  id="type_name"
                  value={newTypeName}
                  onChange={(e) => setNewTypeName(e.target.value)}
                  placeholder="e.g. High-speed Pump"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="type_description">Description (optional)</Label>
                <Input
                  id="type_description"
                  value={newTypeDescription}
                  onChange={(e) => setNewTypeDescription(e.target.value)}
                  placeholder="Short description of this machinery type"
                />
              </div>
              {saveTypeError && (
                <p className="text-sm text-destructive">{saveTypeError}</p>
              )}
            </div>
            <DialogFooter>
              <Button
                variant="outline"
                onClick={() => setIsCreateTypeOpen(false)}
                disabled={savingType}
              >
                Cancel
              </Button>
              <Button
                onClick={async () => {
                  if (!newTypeName.trim()) {
                    setSaveTypeError('Type name is required.');
                    return;
                  }
                  setSavingType(true);
                  setSaveTypeError(null);
                  try {
                    if (editingTypeId) {
                      // Update existing type
                      const updated = await updateMachineryType(
                        editingTypeId,
                        {
                          type_name: newTypeName.trim(),
                          description: newTypeDescription || undefined,
                        },
                        accessToken,
                      );
                      setTypes((prev) =>
                        prev.map((t) =>
                          t.MachineryTypeID === editingTypeId ? updated : t,
                        ),
                      );
                    } else {
                      // Create new type
                      const created = await createMachineryType(
                        {
                          type_name: newTypeName.trim(),
                          description: newTypeDescription || undefined,
                        },
                        accessToken,
                      );
                      setTypes((prev) => [...prev, created]);
                      setSelectedType(String(created.MachineryTypeID));
                    }
                    setIsCreateTypeOpen(false);
                  } catch (err) {
                    setSaveTypeError(
                      err instanceof Error
                        ? err.message
                        : editingTypeId
                        ? 'Failed to update type.'
                        : 'Failed to create type.',
                    );
                  } finally {
                    setSavingType(false);
                  }
                }}
                disabled={savingType}
              >
                {savingType
                  ? 'Saving…'
                  : editingTypeId
                  ? 'Update type'
                  : 'Create type'}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}

      {/* Create Machinery Dialog */}
      {canManageMachinery && (
        <Dialog open={isCreateOpen} onOpenChange={(open) => {
          setIsCreateOpen(open);
          if (!open) {
            setNewAssetTag('');
            setNewMachineName('');
            setNewTypeId('');
            setNewLocation('');
            setNewStatus('OPERATIONAL');
            setSuggestedAssetTag(null);
            setIsAssetTagAutoGenerated(false);
            setValidationErrors({});
            setSaveError(null);
          }
        }}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>New machinery</DialogTitle>
              <DialogDescription>
                Register a new machine/asset and link it to a machinery type.
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-4 py-2">
              <div className="space-y-2">
                <Label htmlFor="asset_tag">Asset tag</Label>
                {suggestedAssetTag && isAssetTagAutoGenerated && (
                  <p className="text-xs text-muted-foreground mb-1">
                    Suggested: <span className="font-mono">{suggestedAssetTag}</span>
                  </p>
                )}
                <Input
                  id="asset_tag"
                  value={newAssetTag}
                  onChange={(e) => {
                    setNewAssetTag(e.target.value);
                    setIsAssetTagAutoGenerated(false);
                    setSuggestedAssetTag(null);
                  }}
                  onBlur={() => {
                    if (!newAssetTag && suggestedAssetTag) {
                      setNewAssetTag(suggestedAssetTag);
                      setIsAssetTagAutoGenerated(true);
                    }
                  }}
                  placeholder={suggestedAssetTag || "e.g. HP-A12"}
                  className={cn(
                    isAssetTagAutoGenerated && "border-dashed border-warning bg-warning/5"
                  )}
                />
                {validationErrors.assetTag && (
                  <p className="text-xs text-destructive">{validationErrors.assetTag}</p>
                )}
              </div>
              <div className="space-y-2">
                <Label htmlFor="machine_name">Machine name</Label>
                <Input
                  id="machine_name"
                  value={newMachineName}
                  onChange={(e) => setNewMachineName(e.target.value)}
                  onBlur={(e) => {
                    const formatted = normalizeDisplayName(e.target.value);
                    setNewMachineName(formatted);
                    setValidationErrors((prev) => ({ ...prev, machineName: undefined }));
                  }}
                  placeholder="Hydraulic Pump A-12"
                />
                {validationErrors.machineName && (
                  <p className="text-xs text-destructive">{validationErrors.machineName}</p>
                )}
              </div>
              <div className="space-y-2">
                <Label htmlFor="machinery_type">Machinery type</Label>
                <Select
                  value={newTypeId}
                  onValueChange={(val) => {
                    setNewTypeId(val);
                    // Auto-suggest asset tag if empty
                    if (!newAssetTag) {
                      const suggestion = generateAssetTagSuggestion(val);
                      setSuggestedAssetTag(suggestion);
                      setIsAssetTagAutoGenerated(true);
                    }
                  }}
                >
                  <SelectTrigger id="machinery_type">
                    <SelectValue placeholder="Select type" />
                  </SelectTrigger>
                  <SelectContent>
                    {types.map((t) => (
                      <SelectItem key={t.MachineryTypeID} value={String(t.MachineryTypeID)}>
                        {t.TypeName}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="location">Location (optional)</Label>
                <Input
                  id="location"
                  value={newLocation}
                  onChange={(e) => setNewLocation(e.target.value)}
                  onBlur={(e) => {
                    const formatted = normalizeDisplayName(e.target.value);
                    setNewLocation(formatted);
                  }}
                  placeholder="e.g. Production Hall A"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="status">Status</Label>
                <Select
                  value={newStatus}
                  onValueChange={(val) => setNewStatus(val as typeof newStatus)}
                >
                  <SelectTrigger id="status">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="OPERATIONAL">Operational</SelectItem>
                    <SelectItem value="MAINTENANCE">Maintenance</SelectItem>
                    <SelectItem value="OUT_OF_SERVICE">Out of Service</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              {saveError && (
                <p className="text-sm text-destructive">{saveError}</p>
              )}
            </div>
            <DialogFooter>
              <Button
                variant="outline"
                onClick={() => setIsCreateOpen(false)}
                disabled={saving}
              >
                Cancel
              </Button>
              <Button
                onClick={async () => {
                  // Use suggested asset tag if empty
                  const finalAssetTag = newAssetTag || suggestedAssetTag || '';
                  const finalMachineName = normalizeDisplayName(newMachineName);
                  
                  if (!finalAssetTag || !finalMachineName || !newTypeId) {
                    setSaveError('Asset tag, name, and type are required.');
                    return;
                  }
                  
                  setSaving(true);
                  setSaveError(null);
                  setValidationErrors({});
                  
                  try {
                    const created = await createMachinery(
                      {
                        asset_tag: finalAssetTag,
                        machine_name: finalMachineName,
                        machinery_type_id: Number(newTypeId),
                        location: newLocation ? normalizeDisplayName(newLocation) : undefined,
                        status: newStatus,
                      } as any,
                      accessToken,
                    );
                    // Refresh list for the created machine's type
                    const typeId = created.MachineryTypeID;
                    const data = await listMachineryByType(typeId, {}, accessToken);
                    setMachines(data);
                    const createdUi = data.find((m) => m.code === created.AssetTag);
                    setSelectedMachine(createdUi ?? data[0] ?? null);
                    setSelectedType(String(typeId));
                    setIsCreateOpen(false);
                  } catch (err) {
                    const errorMessage = err instanceof Error ? err.message : 'Failed to create machinery.';
                    setSaveError(errorMessage);
                    
                    // Parse backend errors for field-specific validation
                    if (errorMessage.includes('Asset tag')) {
                      setValidationErrors((prev) => ({ ...prev, assetTag: errorMessage }));
                    } else if (errorMessage.includes('Machine name')) {
                      setValidationErrors((prev) => ({ ...prev, machineName: errorMessage }));
                    }
                  } finally {
                    setSaving(false);
                  }
                }}
                disabled={saving}
              >
                {saving ? 'Saving…' : 'Create'}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}

      {/* Edit Machinery Dialog */}
      {canManageMachinery && selectedMachine && (
        <Dialog
          open={isEditOpen}
          onOpenChange={(open) => {
            setIsEditOpen(open);
            if (!open) {
              setEditAssetTag('');
              setEditMachineName('');
              setEditTypeId('');
              setEditLocation('');
              setEditStatus('OPERATIONAL');
              setEditValidationErrors({});
              setEditError(null);
            }
          }}
        >
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Edit machinery</DialogTitle>
              <DialogDescription>
                Update this machine&apos;s details. Names and locations use the same
                formatting rules as bulk import.
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-4 py-2">
              <div className="space-y-2">
                <Label htmlFor="edit_asset_tag">Asset tag</Label>
                <Input
                  id="edit_asset_tag"
                  value={editAssetTag}
                  onChange={(e) => {
                    setEditAssetTag(e.target.value);
                    setEditValidationErrors((prev) => ({ ...prev, assetTag: undefined }));
                  }}
                  placeholder="e.g. HP-A12"
                />
                {editValidationErrors.assetTag && (
                  <p className="text-xs text-destructive">
                    {editValidationErrors.assetTag}
                  </p>
                )}
              </div>
              <div className="space-y-2">
                <Label htmlFor="edit_machine_name">Machine name</Label>
                <Input
                  id="edit_machine_name"
                  value={editMachineName}
                  onChange={(e) => setEditMachineName(e.target.value)}
                  onBlur={(e) => {
                    const formatted = normalizeDisplayName(e.target.value);
                    setEditMachineName(formatted);
                    setEditValidationErrors((prev) => ({
                      ...prev,
                      machineName: undefined,
                    }));
                  }}
                  placeholder="Hydraulic Pump A-12"
                />
                {editValidationErrors.machineName && (
                  <p className="text-xs text-destructive">
                    {editValidationErrors.machineName}
                  </p>
                )}
              </div>
              <div className="space-y-2">
                <Label htmlFor="edit_machinery_type">Machinery type</Label>
                <Select
                  value={editTypeId}
                  onValueChange={(val) => setEditTypeId(val)}
                >
                  <SelectTrigger id="edit_machinery_type">
                    <SelectValue placeholder="Select type" />
                  </SelectTrigger>
                  <SelectContent>
                    {types.map((t) => (
                      <SelectItem
                        key={t.MachineryTypeID}
                        value={String(t.MachineryTypeID)}
                      >
                        {t.TypeName}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="edit_location">Location (optional)</Label>
                <Input
                  id="edit_location"
                  value={editLocation}
                  onChange={(e) => setEditLocation(e.target.value)}
                  onBlur={(e) => {
                    const formatted = normalizeDisplayName(e.target.value);
                    setEditLocation(formatted);
                  }}
                  placeholder="e.g. Production Hall A"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="edit_status">Status</Label>
                <Select
                  value={editStatus}
                  onValueChange={(val) =>
                    setEditStatus(val as typeof editStatus)
                  }
                >
                  <SelectTrigger id="edit_status">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="OPERATIONAL">Operational</SelectItem>
                    <SelectItem value="MAINTENANCE">Maintenance</SelectItem>
                    <SelectItem value="OUT_OF_SERVICE">Out of Service</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              {editError && (
                <p className="text-sm text-destructive">{editError}</p>
              )}
            </div>
            <DialogFooter>
              <Button
                variant="outline"
                onClick={() => setIsEditOpen(false)}
                disabled={editSaving}
              >
                Cancel
              </Button>
              <Button
                onClick={async () => {
                  if (!selectedMachine) return;
                  const finalAssetTag = editAssetTag.trim();
                  const finalMachineName = normalizeDisplayName(editMachineName);

                  if (!finalAssetTag || !finalMachineName || !editTypeId) {
                    setEditError('Asset tag, name, and type are required.');
                    return;
                  }

                  setEditSaving(true);
                  setEditError(null);
                  setEditValidationErrors({});

                  try {
                    const updated = await updateMachinery(
                      selectedMachine.id,
                      {
                        asset_tag: finalAssetTag,
                        machine_name: finalMachineName,
                        machinery_type_id: Number(editTypeId),
                        location: editLocation
                          ? normalizeDisplayName(editLocation)
                          : undefined,
                        status: editStatus,
                      } as any,
                      accessToken,
                    );

                    // Refresh list for current type selection
                    await loadMachinesForSelection(selectedType, accessToken);

                    // Try to keep the same selected machine
                    setSelectedMachine((prev) => {
                      if (!prev) return prev;
                      const match = machines.find(
                        (m) => m.id === prev.id,
                      );
                      if (match) return match;
                      return prev;
                    });

                    setIsEditOpen(false);
                  } catch (err) {
                    const errorMessage =
                      err instanceof Error
                        ? err.message
                        : 'Failed to update machinery.';
                    setEditError(errorMessage);
                    if (errorMessage.includes('Asset tag')) {
                      setEditValidationErrors((prev) => ({
                        ...prev,
                        assetTag: errorMessage,
                      }));
                    } else if (errorMessage.includes('Machine name')) {
                      setEditValidationErrors((prev) => ({
                        ...prev,
                        machineName: errorMessage,
                      }));
                    }
                  } finally {
                    setEditSaving(false);
                  }
                }}
                disabled={editSaving}
              >
                {editSaving ? 'Saving…' : 'Save changes'}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}

      {/* Maintenance Confirmation Dialog */}
      {selectedMachine && (
        <Dialog open={maintenanceConfirmOpen} onOpenChange={setMaintenanceConfirmOpen}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>
                {maintenanceAction === 'start'
                  ? 'Move to Maintenance'
                  : 'Move to Operational'}
              </DialogTitle>
              <DialogDescription>
                {maintenanceAction === 'start'
                  ? `Are you sure you want to move "${selectedMachine.name}" to maintenance? This will start a maintenance session and all subsequent spare part requests for this machinery will be linked to this session.`
                  : `Are you sure you want to move "${selectedMachine.name}" back to operational? This will end the current maintenance session.`}
              </DialogDescription>
            </DialogHeader>
            <DialogFooter>
              <Button
                variant="outline"
                onClick={() => {
                  setMaintenanceConfirmOpen(false);
                  setMaintenanceAction(null);
                }}
                disabled={maintenanceLoading}
              >
                Cancel
              </Button>
              <Button
                variant={maintenanceAction === 'end' ? 'default' : 'destructive'}
                onClick={async () => {
                  if (!selectedMachine || !accessToken) return;
                  const machineId = selectedMachine.id;
                  setMaintenanceLoading(true);
                  try {
                    if (maintenanceAction === 'start') {
                      await startMaintenance(machineId, undefined, accessToken);
                    } else {
                      await endMaintenance(machineId, undefined, accessToken);
                    }
                    // Refresh machinery list
                    if (selectedType === 'all') {
                      const allMachines: Machinery[] = [];
                      for (const t of types) {
                        try {
                          const data = await listMachineryByType(t.MachineryTypeID, {}, accessToken);
                          allMachines.push(...data);
                        } catch {
                          // ignore failures per type
                        }
                      }
                      setMachines(allMachines);
                      const refreshed = allMachines.find((m) => m.id === machineId);
                      if (refreshed) setSelectedMachine(refreshed);
                    } else {
                      const typeId = Number(selectedType);
                      const data = await listMachineryByType(typeId, {}, accessToken);
                      setMachines(data);
                      const refreshed = data.find((m) => m.id === machineId);
                      if (refreshed) setSelectedMachine(refreshed);
                    }
                    setMaintenanceConfirmOpen(false);
                    setMaintenanceAction(null);
                  } catch (err) {
                    console.error(`Failed to ${maintenanceAction === 'start' ? 'start' : 'end'} maintenance:`, err);
                  } finally {
                    setMaintenanceLoading(false);
                  }
                }}
                disabled={maintenanceLoading}
              >
                {maintenanceLoading
                  ? 'Processing...'
                  : maintenanceAction === 'start'
                  ? 'Move to Maintenance'
                  : 'Move to Operational'}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}
    </div>
  );
};

export default MachineryPage;
